name: Minecraft Commit Tree

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-tree:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Minecraft Commit Tree
        uses: nivinvysakh/gh-tree@v1.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          tree-type: "oak"
          city: "Manchester"
          weather: "auto"
          days: "140"
          pr-days: "14"
          show-signpost: "true"
          show-bee: "true"
