name: 🌸 Minecraft Commit Tree

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: minecraft-commit-tree
  cancel-in-progress: true

jobs:
  update-tree:
    name: Generate Minecraft Commit Tree
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4

      - name: 🌸 Generate Minecraft Commit Tree
        uses: nivinvysakh/gh-tree@v1.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

          tree-type: "sakura"
          city: "Manchester"
          weather: "auto"

          days: "140"
          pr-days: "14"

          show-signpost: "true"
          show-bee: "true"
